# 客户端配置
SatelliteID = "s0"

# 卫星服务区间
ServiceRangeLeft = 1
ServiceRangeRight = 100

# HTTP服务端口
HttpServerPort = "19999"

# fabric-app 地址
FabricAppHostPath = "http://124.71.187.170:8080"

# 私钥加密密码
PrivateKeyPwd = "elden"